### ISSUE TITLE
Store OAuth token in a `videostokens` table instead of storing in them in the plugin’s settings

### ISSUE THREAD

**Issue by benjamindavid** [dukt/videos#14]
Will also fix an issue with project config where OAuth tokens get stored in the `project.yaml` file when `allowAdminChanges` is set to `false`.

**Comment by ademers** [comment]
I had to connect to YouTube from the Staging site because Google wouldn't accept my Redirect URI in local dev because of `.test` TLD:  http://example.test/index.php?p=admin/actions/videos/oauth/callback Now my `project.yaml` in Staging is contains a `tokens` section and my local dev doesn't. If these are stored in the DB, I could just pull it down from Staging to Dev, right? In the meantime, should I just copy `tokens` from Staging `project.yaml` to Dev `project.yaml`? Thanks~
